
default: &default
  adapter: postgresql
  encoding: unicode
  database: default_database
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
